# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-15 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramApp', '0002_program_registration_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program_registration',
            name='tanggal_lahir',
        ),
    ]
