# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-17 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramApp', '0003_remove_program_registration_tanggal_lahir'),
    ]

    operations = [
        migrations.CreateModel(
            name='program_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('konten', models.TextField(max_length=500)),
            ],
        ),
    ]
