# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-17 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramApp', '0004_program_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_update',
            name='image',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
