# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-19 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramApp', '0004_auto_20181019_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program_registration',
            old_name='test',
            new_name='program',
        ),
    ]
