# Generated by Django 2.1.1 on 2018-12-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramApp', '0006_auto_20181019_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_update',
            name='konten',
            field=models.TextField(max_length=1000),
        ),
    ]
