# Generated by Django 2.1.1 on 2018-12-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramApp', '0007_auto_20181212_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_update',
            name='judul',
            field=models.CharField(max_length=200),
        ),
    ]
