# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-16 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeritaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_update',
            name='konten',
            field=models.TextField(max_length=400),
        ),
    ]
