# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-18 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BeritaApp', '0002_auto_20181016_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_update',
            name='image',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
