# Generated by Django 2.1.1 on 2018-12-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeritaApp', '0003_news_update_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_update',
            name='konten',
            field=models.TextField(max_length=1000),
        ),
    ]
